=== benjamincarney/EECS-Faculty-Salary-Predictor/SalaryReleaseData/EECS_Dept_Salary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="EECS_Dept_Salary" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="EECS_Dept_Salary">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="NAME" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CAMPUS" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="APPOINTMENT_x0020_TITLE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="APPOINTING_x0020_DEPT" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="APPT_x0020_ANNUAL_x0020_FTR" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="APPT_x0020_FTR_x0020_BASIS" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="APPT_x0020_FRACTION" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
<xsd:element name="AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== benjamincarney/EECS-Faculty-Salary-Predictor/SalaryReleaseData/EECS_Dept_Salary.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="EECS_Dept_Salary.xsd" generated="2019-03-27T21:14:07">
<EECS_Dept_Salary>
<ID>2</ID>
<NAME>A,Yongga</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>RESEARCH FELLOW</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>60000</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>30000</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>144</ID>
<NAME>Ackerman,Mark Steven</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Professor</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>170420</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>9-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>0.5</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>85210</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>316</ID>
<NAME>Aerts,William</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>External Relations Director</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>100000</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>0.5</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>0</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>323</ID>
<NAME>Afshari,Ehsan</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>ASSOC PROFESSOR</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>141130</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>9-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>119960.5</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>377</ID>
<NAME>Ahmadi,Elaheh</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>ASST PROFESSOR</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>101988</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>9-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>101988</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>462</ID>
<NAME>Aktakka,Ethem Erkan</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>ASST RES SCIENTIST</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>96755</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>0.1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>0</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>764</ID>
<NAME>Almomani,Raed</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>LEO Intermittent Lecturer</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>72800</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>8-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>0.4</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>29120</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>905</ID>
<NAME>Anastasopoulos,Achilleas</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>ASSOC PROFESSOR</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>122400</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>9-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>122400</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1000</ID>
<NAME>Anderson,Rose M</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Graphic Designer</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>60400</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>33220</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1023</ID>
<NAME>Andreae,Ashley Taylor</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Student Admin Asst Sr</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>60413</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>60413</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1255</ID>
<NAME>Armstrong,Brian</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Engineer in Research Lead</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE - LNF</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>109400</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>0</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1266</ID>
<NAME>Armstrong,Lisa Lynn</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Bus Admin Staff Specialist</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>163219</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>163219</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1351</ID>
<NAME>Arthur,William</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>LEO Lecturer III</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>90860</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>9-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>90860</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1430</ID>
<NAME>Assanie,Mazin</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Research Computer Specialist</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>74900</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>0</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1435</ID>
<NAME>Asudeh Naee,Abolfazl</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>RESEARCH FELLOW</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>70000</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>0</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1536</ID>
<NAME>Austin,Kathleen Garcia</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>Research Process Sr Manager</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>COE EECS - ECE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>92300</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>12-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
<AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>92300</AMT_x0020_OF_x0020_SALARY_x0020_PAID_x0020_FROM_x0020_GENL_x0020_FUND>
</EECS_Dept_Salary>
<EECS_Dept_Salary>
<ID>1548</ID>
<NAME>Austin,Todd M</NAME>
<CAMPUS>UM_ANN-ARBOR</CAMPUS>
<APPOINTMENT_x0020_TITLE>PROFESSOR</APPOINTMENT_x0020_TITLE>
<APPOINTING_x0020_DEPT>EECS - CSE Division</APPOINTING_x0020_DEPT>
<APPT_x0020_ANNUAL_x0020_FTR>186366</APPT_x0020_ANNUAL_x0020_FTR>
<APPT_x0020_FTR_x0020_BASIS>9-Month</APPT_x0020_FTR_x0020_BASIS>
<APPT_x0020_FRACTION>1</APPT_x0020_FRACTION>
